[package]
name = "ring-compat"
version = "0.0.1"
description = """
Compatibility crate for using RustCrypto's traits with the cryptographic
algorithm implementations from *ring*
"""
authors = ["RustCrypto Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/ring-compat"
repository = "https://github.com/RustCrypto/ring-compat"
categories = ["cryptography", "no-std"]
keywords = ["aead", "digest", "crypto", "ring", "signature"]

[dependencies]
aead = { version = "0.3", optional = true, default-features = false }
digest = { version = "0.9", optional = true }
generic-array = { version = "0.14", default-features = false }
opaque-debug = "0.3"
ring = { version = "0.16", default-features = false }
zeroize = { version = "1", default-features = false }

[dev-dependencies]
hex-literal = "0.2"
digest = { version = "0.9", features = ["dev"] }

[features]
default = ["aead", "alloc", "digest"]
alloc = ["aead/alloc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
