name: ring-compat

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    branches: master
    paths-ignore:
      - README.md

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.65.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --release --no-default-features
      - run: cargo test --release --no-default-features --features aead
      - run: cargo test --release --no-default-features --features digest
      - run: cargo test --release --no-default-features --features signature
      - run: cargo test --release
      - run: cargo test --release --all-features

  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
      - uses: RustCrypto/actions/cargo-hack-install@master
      - name: Test benches build
        run: cargo build --benches
      - run: rm Cargo.lock
      - run: cargo update -Z minimal-versions
      - run: cargo hack test --release --feature-powerset

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.65.0 # MSRV
          components: clippy
      - run: cargo clippy --all --all-features -- -D warnings
